album/urls.py
from django.contrib import admin
from django.urls import path,include
from album import views
# app_name = 'album'
urlpatterns = [
    path('category/',views.category,name='category-list'),
	path('category/<int:category_id>/detail',views.category_detail,name='category-detail'),
    path('photo/<int:pk>/detail',views.PhotoDetailView.as_view(),name='photo-detail'),
    path('photo/<int:pk>/update',views.PhotoUpdate.as_view(),name='photo-update'),
    path('photo/<int:pk>/delete',views.PhotoDelete.as_view(),name='photo-delete'),
    path('photo/create',views.PhotoCreate.as_view(),name='photo-create'),
    path('photo/',views.PhotoListView.as_view(),name='photo-list'),
    path('', views.base, name='base'),
    
]

myapps/urls.py
from django.contrib import admin
from django.urls import path, include
from album import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.base, name='base'),
    path('admin/', admin.site.urls),
    path('album/',include('album.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user_options/', views.user_options, name='user-options'),
    path('create-user/', views.create_user, name='create-user'),
]

album/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse

class Category(models.Model):
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	def __repr__(self):
		return self.name	

class Photo(models.Model):
	category = models.ForeignKey(Category,on_delete=models.PROTECT,null=True,blank=True)
	tittle = models.CharField(max_length=50,default='No tittle')
	photo = models.ImageField(upload_to='photos/')
	pub_date = models.DateField(auto_now_add=True)
	favorite = models.BooleanField(default=False)
	comment = models.CharField(max_length=200,blank=True)

	def get_absolute_url(self):
		return reverse('photo-list')

	def __unicode__(self):
		return self.tittle

	def __str__(self):
		return self.tittle

	def __repr__(self):
		return self.tittle

		

## SIGNALS

@receiver(post_delete,sender=Photo)
def photo_detele(sender,instance,**kwargs):
	""" deletes photo files after object destruction"""
	instance.photo.delete(False)

album/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from album.models import Category,Photo
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic import ListView,DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

@login_required
def base(request):
	context = {'image_count': len(Photo.objects.all())}
	return render(request,'base.html',context)

def first_view(request):
	return HttpResponse("My first view!");

@login_required
def category(request):
	category_list = Category.objects.all()
	context = {'object_list': category_list}
	return render(request,'album/category.html',context)

@login_required
def category_detail(request,category_id):
	category = Category.objects.get(id=category_id)
	context = {'object':category}
	return render(request,'album/category_detail.html',context)

@login_required
def user_options(request):
	return render(request,'album/user_options.html')

def create_user(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/album/')
			# context = {'image_count': len(Photo.objects.all())}
			# return render(request, 'base.html', context)
	else:
		form = UserCreationForm()
	context = {"form":form}
	return render(request,'registration/user_creation.html',context)

class PhotoListView(LoginRequiredMixin,ListView):
	model = Photo

class PhotoDetailView(LoginRequiredMixin,DetailView):
	model = Photo


class PhotoUpdate(LoginRequiredMixin,UpdateView):
	model = Photo
	fields = '__all__'

class PhotoCreate(LoginRequiredMixin,CreateView):
	model = Photo
	fields = '__all__'


class PhotoDelete(LoginRequiredMixin,DeleteView):
	model = Photo
	success_url = reverse_lazy('photo-list')
		

album/templates/album/category.html
{% extends 'base.html' %}
{% block section %}
	<h2>Category</h2>
	<hr>
{% endblock section %}

{% block maincontent %}
	<div>
	<ul>
		{% for c in object_list %}
		<li><a href="{% url 'category-detail' c.pk %}">
			{{ c.name }}
		</a></li>
		{% endfor %}
		
	</ul>
	</div>
{% endblock maincontent %}

album/templates/album/category_detail.html
{% extends 'base.html' %}
{% load static %}

{% block section %}
<h1>Photo list</h1>
<h2> {{ object.name }} </h2>
<hr>
{% endblock section %}

{% block maincontent %}
<div>
	<table border="1px">
		<tr>
			{% for p in object.photo_set.all %}
			<td>
				<div>{{ p.tittle }}</div>
				<div>
					<a href="{% url 'photo-detail' p.id %}">
					<img src="{% static p.photo.url %}" alt="{{ p.tittle }}" style="width:200px;height: 200px;"></a>
				</div>
			</td>
			{% endfor %}
		</tr>
	</table>
</div>
{% endblock maincontent %}

album/templates/album/photo_confirm_delete.html
{% extends 'base.html' %}

{% block maincontent %}
	<form action="" method="post">{% csrf_token %}
	<p>Delete "{{ object.tittle }}"?</p>
	<input type="submit" value="Confirm"/>
	<a class='btn' href="{% url 'photo-list' %}">Cancel</a>
	</form>
{% endblock maincontent %}

album/templates/album/photo_detail.html
{% extends 'base.html' %}
{% load static %}

{% block section %}
<h2>
	{{ object.tittle }}
	{% if object.favorite %}
		&#9733;
	{% else %}
		&#9734;
	{% endif %}
	{% if object.category_id %}
		(<a href='{% url "category-detail"  object.category_id %}'>{{ object.category }}</a>)
	{% endif %}
</h2>
<p><strong>Comments: </strong>{{object.comment|default:"no comments"}}</p>
<a href='{% url "photo-update" object.id %}'>Edit</a>
<a href='{% url "photo-delete" object.id %}'>Delete</a>
<hr>
{% endblock section %}

{% block maincontent %}
<div>
	<div>
		<img src="{% static object.photo.url %}" alt="object.tittle" style="width: 550px;height: 420px"/>
	</div>
</div>
{% endblock maincontent %}

album/templates/album/photo_form.html
{% extends "base.html" %}

{% block maincontent %}
	<form enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Save</button>
		<a class="btn" href="{% url 'photo-list' %}">Cancel</a>
	</form>
{% endblock maincontent %}

album/templates/album/photo_list.html
{% extends 'base.html' %}

{% load static %}

{% block section %}
    <h2>Photo</h2> 
    <hr>
{% endblock section %}

{% block maincontent %}
    <div class="row well">
        {% for p in object_list.all %}
            <div class="col-md-4 well">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ p.tittle }}</h3>
                    </div>
                    <div class="panel-body">
                        <a href="{% url 'photo-detail' p.id %}">
                            <img src="{% static p.photo.url %}" style="width:200px;height:200px;"/>
                        </a>
                    </div>
                    <div class="panel-footer">
                        {% if p.comment %}
                            {{ p.comment }}
                        {% else %}
                            <a href="{% url 'photo-update' p.id %}">edit comments</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock maincontent %}

album/templates/album/user_options.html
{% extends 'base.html' %}
{% load static %}

{% block section %}
<h2>
    User Options
</h2>
<hr>
{% endblock section %}

{% block maincontent %}
<div>
    <ul>
        <li><a href='{% url "password_reset" %}'>Password reset</a></li>
        <li><a href='{% url "password_change" %}'>Password Change</a></li>
    </ul>
</div>
{% endblock maincontent %}

album/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Albums</title>
	<!-- CDN Boostrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" ​></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
</head>
<body>
	<!-- Navbar -->
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'base' %}">ALBUM</a>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'category-list' %}">Category <span class="sr-only">(current)</span></a></li>
					<li><a href="{% url 'photo-list' %}">Photo</a></li>
					{% if user.is_authenticated %}
					<li><a href="#">Logged as <strong>{{ user.username }}</strong></a></li>
					<li><a href="{% url 'user-options' %}"><strong>User Options</strong></a></li>
					{% else %}
					<li><a href="{% url 'login' %}">Login</a></li>
					<li><a href="{% url 'login' %}">Create Account</a></li>
					{% endif %}
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Action <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="{% url 'photo-create' %}">Upload</a></li>
							<li class="divider"></li>
							<li><a href="{% url 'logout' %}">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	
	<div class="container">
		{% block section %}
		{% endblock section %}
	</div>

	<div class="container">
		{% block maincontent %}
		{% endblock maincontent %}
	</div>

	{% if image_count %}
		<div class="card text-center">
			<i class="fa fa-picture-o fa-5x"></i>
			<h3 class="count-title count-number">{{image_count}}</h3>
			<p>Images in album</p>
		</div>
	{% endif %}
</body>
</html>

album/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Albums</title>
	<!-- CDN Boostrap -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"> -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css"> -->
	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<body>
	<!-- Navbar -->
	<div class="container text-center">
		{% block section %}
		{% endblock section %}
	</div>

	<div class="container">
		{% block maincontent %}
		{% endblock maincontent %}
	</div>
</body>
</html>

album/templates/oldbase.html
	<h1>Juan's PhotoAlbum</h1>
	<ul>
		<li><a href="{% url 'category-list' %}">Categories</a></li>
		<li><a href="{% url 'photo-list' %}">Photos</a></li>
		<li><a href="{% url 'photo-create' %}">Upload</a></li>
	</ul>
	<hr>
	<div>
		{% block section %}
		{% endblock section %}
	</div>
	<div>
		{% block maincontent %}
		{% endblock maincontent %}
	</div>
</body>
</html>